---
- name: Installation des packages lxc
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lxc
    - lxc-dev
    - yum
  tags:
    - create

- name: Installation des bindings python pour lxc
  pip:
    name: lxc-python2
    state: latest
  tags:
    - create

- name: Création des containers
  lxc_container:
    name: "{{ item.name }}"
    container_log: true
    template: "{{ item.template }}"
    state: stopped
    template_options: "--release {{ item.release }}"
  with_items: "{{ lxc_deploy_containers }}"
  tags:
    - create

- name: Ajout des lignes de configuration supplémentaires
  lineinfile:
    dest: "/var/lib/lxc/{{ item.0.name }}/config"
    line: "{{ item.1 }}"
  with_subelements:
    - "{{ lxc_deploy_containers }}"
    - extra_conf
    - flags:
      skip_missing: True
  tags:
    - create

- name: Installation de python sur les containers
  lxc_container:
    name: "{{ item.name }}"
    container_command: |
      {{ item.pkg_mgr }} update -y
      {{ item.pkg_mgr }} install -y python sudo
  with_items: "{{ lxc_deploy_containers }}"
  tags:
    - create
